# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: '17'
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npx playwright install --with-deps ${{ matrix.browser }} chromium
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.browser }}-win-test-results
          path: test-results
      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress
      - name: Run Tests with Maven
        run: mvn clean test --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
